wiki/wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.entry, name="entry"),
    path("search", views.search, name="search"),
    path("add", views.add, name="add"),
    path("edit/<str:title>", views.edit, name="edit"),
    path("random", views.random, name="random")
]

wiki/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

app_name = "wiki"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/wiki/encyclopedia/forms.py
from django import forms

class EntryForm(forms.Form):
    content = forms.CharField(
        label="", 
        widget=forms.Textarea(attrs={
            'class':'form-control',
            'placeholder':'Enter Markdown Content Here...'
    }))

class NewEntryForm(EntryForm):
    title = forms.CharField(
    label="",
    widget=forms.TextInput(attrs={
        'class':'form-control',
        'placeholder':'Enter Title Here...'
    }))

wiki/wiki/encyclopedia/views.py
from django.shortcuts import render, redirect, reverse
from markdown2 import markdown
from random import randint
from . import util, forms

def index(request):
    return render(request, "encyclopedia/index.html", {                                 # List all entries
        "heading": "All Pages",
        "entries": util.list_entries()
    })

def entry(request, title):
    
    entry = util.get_entry(title)                                                       # Grab entry from disk based on title
    
    if entry:
        return render(request, "encyclopedia/entry.html", {                             # If entry exists, render entry page
        "title": title,
        "entry": markdown(entry)
    })

    return render(request, "encyclopedia/404.html")                                     # If no entry exist, render error page

def random(request):

    entries = util.list_entries()                                                       # Grab all entries
    n = randint(0, len(entries))                                                        # Generate a random integer
    return redirect(reverse("encyclopedia:entry", args=(entries[n-1],)))                # Redirect user to random page    

def search(request):

    if request.method == "GET":
        
        query = request.GET.get('q')                                                    # Grab user query
        query_lower = query.lower()                                                     # Convert user query to lowercase

        entries = util.list_entries()                                                   # Grab list of all entries
        entries_lower = list(map(str.lower, entries))                                   # Lowercase all entry titles

        search_results = []                                                             # If query matches an entry title
        for i in range(len(entries_lower)):                                             # regardless of case, redirect to 
            if query_lower == entries_lower[i]:                                         # entry page
                return redirect(reverse('encyclopedia:entry', args=(entries[i],)))
            elif query_lower in entries_lower[i] or entries_lower[i] in query_lower:    # If query or entry title is a substring
                search_results.append(entries[i])                                       # of one another add to results list
        
        return render(request, "encyclopedia/index.html", {                             # Display search results to user if
            "heading": f"Search Results for {query}",                                   # exact match not found
            "entries": search_results
        })

def add(request):
    
    if request.method == "POST":                                                        # Check request method
        form = forms.NewEntryForm(request.POST)                                         # Populate form instance w/ data from request
        
        if form.is_valid():                                                             # Validate form
            title = form.cleaned_data["title"]                                          # Grab entry title user submitted 
            
            if util.entry_exists(title):                                                # Ensure that another entry with title
                return render(request, "encyclopedia/add.html", {                       # does not exist. If True, display error
                    "form": form,                                                       # to user
                    "error_msg": "Sorry That Title Already Exists... Please choose another :("
                })

            content = form.cleaned_data["content"]                                      # Grab entry content user submitted
            util.save_entry(title, content)                                             # Save new entry to disk
            return redirect(reverse('encyclopedia:entry', args=(title,)))               # Redirect user to new entry page

        return render(request, "encyclopedia/add.html", {                               # If form is invalid, re-render page with
            "form": form,                                                               # existing form information and display
            "error_msg": "Unable to Validate Form."                                     # error to user.
        })
        
        
    return render(request, "encyclopedia/add.html", {                                   # If request method is anything other than
        "form": forms.NewEntryForm(),                                                   # POST, render page with blank form.
        "error_msg": None
    })

def edit(request, title):

    if request.method == "POST":                                                        # If form can be validated, update
        form = forms.EntryForm(request.POST)                                            # content of entry.

        if form.is_valid():
            content = form.cleaned_data["content"]

            util.save_entry(title, content)

            return redirect(reverse("encyclopedia:entry", args=(title,)))
        
        return render(request, "encyclopedia/edit.html", {
            "form": form,
            "error_msg": "Unable to Validate Form."
        })

    return render(request, "encyclopedia/edit.html", {                                  # If request method not POST, render page,
        "title": title,                                                                 # with entry content populating edit form                              
        "form": forms.EntryForm(initial={                                        
            'content': util.get_entry(title)
            }),                                            
        "error_msg": None
    })

wiki/wiki/encyclopedia/templates/encyclopedia/add.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia | New Page
{% endblock %}

{% block body %}

    {% if error_msg %}
        <div class="alert alert-warning w-50">
           {{ error_msg }} 
        </div>
    {% endif %}

    <h1>Create New Page</h1>
    <form action="{% url 'encyclopedia:add' %}" method="post" class="w-50">
        {% csrf_token %}
        <div class="form-group">
            {{ form.title }}
        </div>
        <div class="form-group">
            {{ form.content }}
        </div>
        <div class="form-group">
            <input type="submit" class="form-control" value="Save">
        </div>
    </form>

{% endblock %}

wiki/wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia | Edit {{ title }}
{% endblock %}

{% block body %}

    {% if error_msg %}
        <div class="alert alert-warning w-50">
           {{ error_msg }} 
        </div>
    {% endif %}

    <h1>Editing {{ title }} Page</h1>
    <form action="{% url 'encyclopedia:edit' title %}" method="post" class="w-50">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                {{ field }}
            </div>
        {% endfor %}
        <div class="form-group">
            <input type="submit" class="form-control" value="Save">
        </div>
    </form>

{% endblock %}

wiki/wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia | {{ title }}
{% endblock %}

{% block body %}
    
    {{ entry | safe }}

{% endblock %}

wiki/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>{{ heading }}</h1>

    <ul>
        {% for entry in entries %}
            <li><a href = "{% url 'encyclopedia:entry' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="get">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:add' %}">Create New Page</a>
                </div>
                {% if title %}
                    <div>
                        <a href="{% url 'encyclopedia:edit' title%}">Edit Current Page</a>
                    </div>
                {% endif %}
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>